/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonasiRouteImport } from './routes/donasi'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAbsensiRouteImport } from './routes/admin/absensi'
import { Route as AdminBannerRouteImport } from './routes/admin/banner'
import { Route as AdminBeritaRouteImport } from './routes/admin/berita'
import { Route as AdminDonasiRouteImport } from './routes/admin/donasi'
import { Route as AdminEventRouteImport } from './routes/admin/event'
import { Route as AdminGaleriRouteImport } from './routes/admin/galeri'
import { Route as AdminLiveRouteImport } from './routes/admin/live'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNotifikasiRouteImport } from './routes/admin/notifikasi'
import { Route as AdminPendaftarRouteImport } from './routes/admin/pendaftar'
import { Route as AdminProgramRouteImport } from './routes/admin/program'
import { Route as AdminSertifikatRouteImport } from './routes/admin/sertifikat'
import { Route as AdminSponsorRouteImport } from './routes/admin/sponsor'
import { Route as AdminUserRouteImport } from './routes/admin/user'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as BeritaSlugRouteImport } from './routes/berita/$slug'
import { Route as DaftarSlugRouteImport } from './routes/daftar.$slug'
import { Route as EventIndexRouteImport } from './routes/event/index'
import { Route as EventSlugRouteImport } from './routes/event/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiRoute = DonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAbsensiRoute = AdminAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBannerRoute = AdminBannerRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDonasiRoute = AdminDonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventRoute = AdminEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGaleriRoute = AdminGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotifikasiRoute = AdminNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPendaftarRoute = AdminPendaftarRouteImport.update({
  id: '/pendaftar',
  path: '/pendaftar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProgramRoute = AdminProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSertifikatRoute = AdminSertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSponsorRoute = AdminSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarSlugRoute = DaftarSlugRouteImport.update({
  id: '/daftar/$slug',
  path: '/daftar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/donasi': typeof DonasiRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/donasi': typeof AdminDonasiRoute
  '/admin/event': typeof AdminEventRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/program': typeof AdminProgramRoute
  '/admin/sertifikat': typeof AdminSertifikatRoute
  '/admin/sponsor': typeof AdminSponsorRoute
  '/admin/user': typeof AdminUserRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/daftar/$slug': typeof DaftarSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/event/': typeof EventIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/donasi': typeof DonasiRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/donasi': typeof AdminDonasiRoute
  '/admin/event': typeof AdminEventRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/program': typeof AdminProgramRoute
  '/admin/sertifikat': typeof AdminSertifikatRoute
  '/admin/sponsor': typeof AdminSponsorRoute
  '/admin/user': typeof AdminUserRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/daftar/$slug': typeof DaftarSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/event': typeof EventIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/donasi': typeof DonasiRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/admin/absensi': typeof AdminAbsensiRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/donasi': typeof AdminDonasiRoute
  '/admin/event': typeof AdminEventRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pendaftar': typeof AdminPendaftarRoute
  '/admin/program': typeof AdminProgramRoute
  '/admin/sertifikat': typeof AdminSertifikatRoute
  '/admin/sponsor': typeof AdminSponsorRoute
  '/admin/user': typeof AdminUserRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/daftar/$slug': typeof DaftarSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/event/': typeof EventIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/donasi'
    | '/galeri'
    | '/kontak'
    | '/program'
    | '/tentang'
    | '/admin/absensi'
    | '/admin/banner'
    | '/admin/berita'
    | '/admin/donasi'
    | '/admin/event'
    | '/admin/galeri'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifikasi'
    | '/admin/pendaftar'
    | '/admin/program'
    | '/admin/sertifikat'
    | '/admin/sponsor'
    | '/admin/user'
    | '/berita/$slug'
    | '/daftar/$slug'
    | '/event/$slug'
    | '/admin/'
    | '/berita/'
    | '/event/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/donasi'
    | '/galeri'
    | '/kontak'
    | '/program'
    | '/tentang'
    | '/admin/absensi'
    | '/admin/banner'
    | '/admin/berita'
    | '/admin/donasi'
    | '/admin/event'
    | '/admin/galeri'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifikasi'
    | '/admin/pendaftar'
    | '/admin/program'
    | '/admin/sertifikat'
    | '/admin/sponsor'
    | '/admin/user'
    | '/berita/$slug'
    | '/daftar/$slug'
    | '/event/$slug'
    | '/admin'
    | '/berita'
    | '/event'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/donasi'
    | '/galeri'
    | '/kontak'
    | '/program'
    | '/tentang'
    | '/admin/absensi'
    | '/admin/banner'
    | '/admin/berita'
    | '/admin/donasi'
    | '/admin/event'
    | '/admin/galeri'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifikasi'
    | '/admin/pendaftar'
    | '/admin/program'
    | '/admin/sertifikat'
    | '/admin/sponsor'
    | '/admin/user'
    | '/berita/$slug'
    | '/daftar/$slug'
    | '/event/$slug'
    | '/admin/'
    | '/berita/'
    | '/event/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DonasiRoute: typeof DonasiRoute
  GaleriRoute: typeof GaleriRoute
  KontakRoute: typeof KontakRoute
  ProgramRoute: typeof ProgramRoute
  TentangRoute: typeof TentangRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  DaftarSlugRoute: typeof DaftarSlugRoute
  EventSlugRoute: typeof EventSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  EventIndexRoute: typeof EventIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi': {
      id: '/donasi'
      path: '/donasi'
      fullPath: '/donasi'
      preLoaderRoute: typeof DonasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/absensi': {
      id: '/admin/absensi'
      path: '/absensi'
      fullPath: '/admin/absensi'
      preLoaderRoute: typeof AdminAbsensiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/banner': {
      id: '/admin/banner'
      path: '/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AdminBannerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/donasi': {
      id: '/admin/donasi'
      path: '/donasi'
      fullPath: '/admin/donasi'
      preLoaderRoute: typeof AdminDonasiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/event': {
      id: '/admin/event'
      path: '/event'
      fullPath: '/admin/event'
      preLoaderRoute: typeof AdminEventRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/galeri': {
      id: '/admin/galeri'
      path: '/galeri'
      fullPath: '/admin/galeri'
      preLoaderRoute: typeof AdminGaleriRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifikasi': {
      id: '/admin/notifikasi'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi'
      preLoaderRoute: typeof AdminNotifikasiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pendaftar': {
      id: '/admin/pendaftar'
      path: '/pendaftar'
      fullPath: '/admin/pendaftar'
      preLoaderRoute: typeof AdminPendaftarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/program': {
      id: '/admin/program'
      path: '/program'
      fullPath: '/admin/program'
      preLoaderRoute: typeof AdminProgramRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sertifikat': {
      id: '/admin/sertifikat'
      path: '/sertifikat'
      fullPath: '/admin/sertifikat'
      preLoaderRoute: typeof AdminSertifikatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sponsor': {
      id: '/admin/sponsor'
      path: '/sponsor'
      fullPath: '/admin/sponsor'
      preLoaderRoute: typeof AdminSponsorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar/$slug': {
      id: '/daftar/$slug'
      path: '/daftar/$slug'
      fullPath: '/daftar/$slug'
      preLoaderRoute: typeof DaftarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAbsensiRoute: typeof AdminAbsensiRoute
  AdminBannerRoute: typeof AdminBannerRoute
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminDonasiRoute: typeof AdminDonasiRoute
  AdminEventRoute: typeof AdminEventRoute
  AdminGaleriRoute: typeof AdminGaleriRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotifikasiRoute: typeof AdminNotifikasiRoute
  AdminPendaftarRoute: typeof AdminPendaftarRoute
  AdminProgramRoute: typeof AdminProgramRoute
  AdminSertifikatRoute: typeof AdminSertifikatRoute
  AdminSponsorRoute: typeof AdminSponsorRoute
  AdminUserRoute: typeof AdminUserRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAbsensiRoute: AdminAbsensiRoute,
  AdminBannerRoute: AdminBannerRoute,
  AdminBeritaRoute: AdminBeritaRoute,
  AdminDonasiRoute: AdminDonasiRoute,
  AdminEventRoute: AdminEventRoute,
  AdminGaleriRoute: AdminGaleriRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotifikasiRoute: AdminNotifikasiRoute,
  AdminPendaftarRoute: AdminPendaftarRoute,
  AdminProgramRoute: AdminProgramRoute,
  AdminSertifikatRoute: AdminSertifikatRoute,
  AdminSponsorRoute: AdminSponsorRoute,
  AdminUserRoute: AdminUserRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DonasiRoute: DonasiRoute,
  GaleriRoute: GaleriRoute,
  KontakRoute: KontakRoute,
  ProgramRoute: ProgramRoute,
  TentangRoute: TentangRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  DaftarSlugRoute: DaftarSlugRoute,
  EventSlugRoute: EventSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  EventIndexRoute: EventIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
